# Generated by Django 2.1.2 on 2018-11-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_auto_20181125_1044'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
