# Generated by Django 2.1.2 on 2018-10-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coord_x', models.IntegerField()),
                ('coord_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Landscape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='landscape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalMaps.Landscape'),
        ),
    ]
