# Generated by Django 2.1.2 on 2018-11-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world_version',
            name='status_of_world',
            field=models.CharField(choices=[('e', 'enable'), ('d', 'disable'), ('c', 'comingsoon')], max_length=1),
        ),
    ]
