# Generated by Django 2.1.2 on 2018-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20181121_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world_version',
            name='status_of_world',
            field=models.CharField(choices=[('enable', '_enable'), ('disable', '_disable'), ('comingsoon', '_comingsoon')], max_length=10),
        ),
    ]
