# Generated by Django 2.1.2 on 2018-11-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20181121_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.World_version')),
            ],
        ),
    ]
