# Generated by Django 2.1.2 on 2018-11-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_auto_20181125_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clan',
            old_name='name',
            new_name='clan_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='customer_account',
            old_name='name',
            new_name='account_name',
        ),
    ]
