# Generated by Django 2.1.2 on 2018-11-29 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20181128_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='account_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='structure.Customer_Account'),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
