# Generated by Django 2.1.2 on 2018-11-29 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_auto_20181129_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_account',
            name='clan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.Clan'),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_account',
            name='world',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='structure.World_version'),
        ),
    ]
