# Generated by Django 2.1.2 on 2018-12-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_auto_20181129_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_account',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.Clan'),
        ),
    ]
