# Generated by Django 2.1.2 on 2018-12-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0017_auto_20181207_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_settings',
            name='selected_world',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='structure.World_version'),
        ),
    ]
